projectAmazon/Amazon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    
    path('',productos,name='productos'),
    path('login/', iniciarsecion, name='login'),
    path('register/', register, name='register'),
    path('logout/', cerrarSecion, name='logout'),
    path('productos/<int:id>/', detalle_producto, name='detalle_producto'),
    path('masProductos',todos_los_productos,name='todo_los_productos'),
    path('productos/<int:id>/agregar-al-carrito/', agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/', ver_carrito, name='ver_carrito'),
    path('carrito/actualizar/<int:id>/', actualizar_cantidad, name='actualizar_cantidad'),
    path('direccion-y-carrito/', direccion_y_carrito, name='direccion_y_carrito'),
    path('metodo_pago/', metodo_de_pago, name='metodo_de_pago'),
    path('pago-realizado/', pago_realizado, name='pago_realizado'),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectAmazon/projectAmazon/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Amazon.urls')),
]

projectAmazon/Amazon/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from .choices import sexos

# Create your models here.

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cliente')
    nombres = models.CharField(max_length=100)
    telefono = models.CharField(max_length=9)  
    fecha_Nacimiento = models.DateField()
    sexo=models.CharField(max_length=1, choices=sexos, default='-')

    def __str__(self):
        return self.nombres

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    marca = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    material = models.CharField(max_length=100)
    tamaño = models.CharField(max_length=50)
    cantidad = models.PositiveIntegerField()
    imagen = models.ImageField(upload_to='productos/')

    def __str__(self):
        return self.nombre
    
class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Carrito de {self.usuario.username}"

class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.cantidad * self.producto.precio

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre}"

class DireccionEnvio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=9)
    direccion = models.CharField(max_length=255)
    estado = models.CharField(max_length=100)
    codigo_postal = models.CharField(max_length=5)
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

class Cupon(models.Model):
    codigo = models.CharField(max_length=20, unique=True)
    descuento = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.codigo
    
class Pago(models.Model):
    numero_tarjeta = models.CharField(max_length=16)
    fecha_expiracion = models.CharField(max_length=5)
    nombre_propietario = models.CharField(max_length=100)
    cvv = models.CharField(max_length=4)
    guardar_tarjeta = models.BooleanField(default=False)
    fecha_pago = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Pago realizado por {self.nombre_propietario} el {self.fecha_pago}"

projectAmazon/Amazon/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from Amazon.models import Cliente,DireccionEnvio, Pago
from datetime import date
from .choices import sexos


def validate_age_range(value):
    min_age = 18
    max_age = 90
    if value:
        today = date.today()
        age = today.year - value.year - ((today.month, today.day) < (value.month, value.day))
        if age < min_age or age > max_age:
            raise ValidationError(f"La edad debe estar entre {min_age} y {max_age} años.")
        
def no_numeros_validator(value):
    if any(char.isdigit() for char in value):
        raise ValidationError('El campo no debe contener números')
    
def no_letras_validator(value):
    if any(char.isalpha() for char in value):
        raise ValidationError('El campo no debe contener letras')  

class formCliente(forms.Form):
    correo = forms.EmailField(label="Correo electrónico")  
    nombres=forms.CharField(max_length=30,validators=[no_numeros_validator])
    telefono=forms.CharField(max_length=9,validators=[no_letras_validator])
    fecha_Nacimiento=forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), validators=[validate_age_range])
    sexo = forms.ChoiceField(choices=sexos, initial='-')

    class Meta:
        model = Cliente
        fields = ['correo', 'nombres','telefono', 'fecha_Nacimiento','sexo']
    
    def clean_fecha_Nacimiento(self):
        fecha_nacimiento = self.cleaned_data.get('fecha_Nacimiento')
        validate_age_range(fecha_nacimiento)  # Llamar al validador personalizado para fecha de nacimiento
        return fecha_nacimiento


class DireccionEnvioForm(forms.ModelForm):
    nombre=forms.CharField(max_length=30,validators=[no_numeros_validator])
    telefono=forms.CharField(max_length=9,validators=[no_letras_validator])
    direccion=forms.CharField(max_length=30)
    estado=forms.CharField(max_length=30)
    codigo_postal=forms.CharField(max_length=5,validators=[no_letras_validator])

    class Meta:
        model = DireccionEnvio
        fields = ['nombre', 'telefono', 'direccion', 'estado', 'codigo_postal']
    
class PagoForm(forms.Form):
    numero_tarjeta = forms.CharField( max_length=16,validators=[no_letras_validator])
    fecha_expiracion = forms.CharField(max_length=5,validators=[no_letras_validator])
    nombre_propietario = forms.CharField(max_length=100,validators=[no_numeros_validator])
    cvv = forms.CharField(max_length=4,validators=[no_letras_validator])
    guardar_tarjeta = forms.BooleanField( required=False)

    class Meta:
        model = Pago
        fields = ['numero_tarjeta', 'fecha_expiracion', 'nombre_propietario', 'cvv', 'guardar_tarjeta']

projectAmazon/Amazon/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.forms import  UserCreationForm, AuthenticationForm
from Amazon.models import Cliente, Producto, Carrito, ItemCarrito, DireccionEnvio, Pago
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from Amazon.forms import formCliente, DireccionEnvioForm, PagoForm
from django.contrib.auth.decorators import login_required
from decimal import Decimal


# Create your views here.
   
def iniciarsecion(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('productos')
        else:
            return render(request, 'amazon/signin.html', {
                'formLogin': form,
            })
    else:
        form = AuthenticationForm()
        return render(request, 'amazon/signin.html', {
            'formLogin': form
        })
    
def register(request):
    if request.method == "POST":
        formcli = formCliente(request.POST, request.FILES)
        formRegister = UserCreationForm(request.POST)
        if formcli.is_valid() and formRegister.is_valid():
            try:
                correo = formcli.cleaned_data['correo']
                user = formRegister.save(commit=False)  # Guardar usuario
                user.email = correo  # Establecer el correo electrónico del usuario
                user.save()

                Cliente.objects.create(
                    user=user,
                    nombres=formcli.cleaned_data['nombres'],
                    telefono=formcli.cleaned_data['telefono'],
                    fecha_Nacimiento=formcli.cleaned_data['fecha_Nacimiento'],
                    sexo=formcli.cleaned_data['sexo'],

                )
                messages.success(request, 'Usuario registrado exitosamente. Por favor inicia sesión.')
                return render(request, 'Amazon/register_done.html', {'new_user': user})
            except IntegrityError:
                messages.error(request, 'Error: El nombre de usuario ya está en uso.')
    else:
        formcli = formCliente()
        formRegister = UserCreationForm()
    
    return render(request, "amazon/register.html", {
        'formUser': formRegister,
        'formCliente': formcli,
    })

def cerrarSecion(request):
    logout(request)
    return redirect('productos')

def productos(request):
    productos_list = Producto.objects.all()
    return render(request, "amazon/productos.html", {'productos': productos_list})

def todos_los_productos(request):
    productos_list = Producto.objects.all().order_by('?')  # Orden aleatorio
    return render(request, "amazon/total_productos.html", {'productos': productos_list})

def detalle_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    return render(request, 'amazon/detalle_producto.html', {'producto': producto})

@login_required
def agregar_al_carrito(request, id):
    producto = get_object_or_404(Producto, id=id)
    cantidad = int(request.POST.get('cantidad', 1))
    carrito, created = Carrito.objects.get_or_create(usuario=request.user)

    item, created = ItemCarrito.objects.get_or_create(carrito=carrito, producto=producto)
    
    if not created:
        item.cantidad += cantidad
    else:
        item.cantidad = cantidad

    item.save()

    messages.success(request, f'{producto.nombre} se ha agregado al carrito.')
    return redirect('ver_carrito')

@login_required
def ver_carrito(request):
    carrito, created = Carrito.objects.get_or_create(usuario=request.user)
    items = ItemCarrito.objects.filter(carrito=carrito)
    total = sum(item.subtotal() for item in items)
    return render(request, 'amazon/carrito.html', {'items': items, 'total': total})

@login_required
def actualizar_cantidad(request, id):
    item = get_object_or_404(ItemCarrito, id=id, carrito__usuario=request.user)
    cantidad = int(request.POST.get('cantidad', item.cantidad))
    if cantidad > 0:
        item.cantidad = cantidad
        item.save()
    else:
        item.delete()
    return redirect('ver_carrito')

@login_required
def direccion_y_carrito(request):
    carrito_usuario = Carrito.objects.get(usuario=request.user)  # Obtener el carrito del usuario actual
    items_carrito = ItemCarrito.objects.filter(carrito=carrito_usuario)  # Obtener todos los ítems del carrito del usuario actual

    total_parcial = 0
    for item in items_carrito:
        # Calcular el subtotal de cada ítem
        subtotal = item.producto.precio * item.cantidad
        item.subtotal = subtotal
        total_parcial += subtotal
    
    iva = total_parcial * Decimal('0.05')  # Calcular el IVA
    total_con_iva = total_parcial + iva  # Calcular el total con IVA

    user = request.user
    direccion_envio = DireccionEnvio.objects.filter(user=user).first()  # Obtener la dirección de envío existente, si la hay

    if request.method == 'POST':
        form = DireccionEnvioForm(request.POST, instance=direccion_envio)  # Pasar la instancia existente al formulario
        if form.is_valid():
            direccion = form.save(commit=False)  # Guardar la dirección de envío (crea o actualiza)
            direccion.user = user
            direccion.save()
            messages.success(request, 'Dirección guardada correctamente.')
            return redirect('direccion_y_carrito')  # Redirigir a la misma vista para refrescar el contexto
        else:
            messages.error(request, 'Por favor corrige los errores del formulario.')
    else:
        form = DireccionEnvioForm(instance=direccion_envio)  # Inicializar el formulario con la instancia existente

    context = {
        'form': form,
        'items': items_carrito,
        'total_parcial': total_parcial,
        'iva': iva,
        'total_con_iva': total_con_iva,
        'formularioEnviado': direccion_envio is not None,  # Verificar si hay dirección de envío guardada
    }
    
    return render(request, 'amazon/direccion_y_carrito.html', context)

@login_required
def metodo_de_pago(request):
    # Obtener todos los ítems del carrito
    items_carrito = ItemCarrito.objects.all()
    
    # Calcular el total a pagar incluyendo el IVA
    total_parcial = 0
    for item in items_carrito:
        subtotal = item.producto.precio * item.cantidad
        total_parcial += subtotal
    
    iva = total_parcial * Decimal('0.05')  # Calcular el IVA
    total_con_iva = total_parcial + iva  # Calcular el total con IVA

    metodo_pago = None  # Inicializar metodo_pago fuera del bloque POST

    if request.method == 'POST':
        metodo_pago = request.POST.get('metodo_pago')
        form = PagoForm(request.POST)
        if form.is_valid():
            # Procesar los datos del formulario
            Pago.objects.create(
                numero_tarjeta=form.cleaned_data['numero_tarjeta'],
                fecha_expiracion=form.cleaned_data['fecha_expiracion'],
                nombre_propietario=form.cleaned_data['nombre_propietario'],
                cvv=form.cleaned_data['cvv'],
                guardar_tarjeta=form.cleaned_data['guardar_tarjeta'],
            )

            # Lógica adicional según sea necesario, como guardar la tarjeta

            # Redirigir al usuario a la página de pago realizado
            return redirect('pago_realizado')
    else:
        form = PagoForm()
        

    context = {
        'total_a_pagar': total_con_iva,
        'form': form,
    }

    if metodo_pago == 'yape':
        # Lógica para el método de pago con YAPE
        monto_a_cobrar = total_con_iva
        context.update({
            'metodo_pago': 'YAPE',
            'monto_a_cobrar': monto_a_cobrar,
        })
    elif metodo_pago == 'tarjeta':
        # Lógica para el método de pago con tarjeta
        context.update({
            'metodo_pago': 'Tarjeta de Crédito',
        })
    elif request.method == 'POST':
        messages.error(request, 'Selecciona un método de pago válido.')

    return render(request, 'amazon/metodo_de_pago.html', context)

@login_required
def pago_realizado(request):
    # Obtener el carrito del usuario actual
    carrito_usuario = Carrito.objects.get(usuario=request.user)

    # Obtener todos los ítems del carrito del usuario actual
    items_carrito = ItemCarrito.objects.filter(carrito=carrito_usuario)

    # Eliminar todos los ítems del carrito
    items_carrito.delete()
    return render(request, 'amazon/pago_realizado.html')

projectAmazon/Amazon/templates/Amazon/direccion_y_carrito.html
<!-- templates/amazon/direccion_y_carrito.html -->
{% extends "Amazon/base.html" %}
{% load widget_tweaks %}
{% block detalle_prod %}

<style>
    .timeline {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .step {
        display: flex;
        align-items: center;
        width: 30%;
        padding: 20px;
        background-color: #f0f0f0;
        border-radius: 8px;
    }

    .step-number {
        width: 40px;
        height: 40px;
        background-color: #007bff; /* Color base de las bolitas */
        color: white;
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 50%;
        margin-right: 10px;
    }

    .step-content {
        flex: 1;
    }

    .step h4 {
        margin-bottom: 5px;
    }

    .step p {
        font-size: 0.9rem;
        color: #666;
    }

    .completed .step-number {
        background-color: #28a745; /* Color verde para los pasos completados */
    }
</style>

<div class="container mt-5">
    <div class="row">
        <!-- Formulario de Dirección de Envío -->
        <div class="col-md-5">
            <h2>Dirección de Envío</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-1">
                    <label for="id_nombre" class="form-label">Nombre</label>
                    {{ form.nombre|add_class:"form-control" }}
                    {% for error in form.nombre.errors %}
                    <div class="error-message text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-1">
                    <label for="id_telefono" class="form-label">Teléfono</label>
                    {{ form.telefono|add_class:"form-control" }}
                    {% for error in form.telefono.errors %}
                    <div class="error-message text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-1">
                    <label for="id_direccion" class="form-label">Dirección</label>
                    {{ form.direccion|add_class:"form-control" }}
                    {% for error in form.direccion.errors %}
                    <div class="error-message text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-1">
                    <label for="id_estado" class="form-label">Región</label>
                    {{ form.estado|add_class:"form-control" }}
                    {% for error in form.estado.errors %}
                    <div class="error-message text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-1">
                    <label for="id_codigo_postal" class="form-label">Código Postal</label>
                    {{ form.codigo_postal|add_class:"form-control" }}
                    {% for error in form.codigo_postal.errors %}
                    <div class="error-message text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                
                <button type="submit" class="btn btn-primary" {% if formularioEnviado %}disabled{% endif %}>Guardar Dirección</button>
                {% if formularioEnviado %}
                <span class="text-success ml-2">Dirección guardada</span>
                {% else %}
                <span class="text-danger ml-2">Por favor completa la dirección para proceder con el pago.</span>
                {% endif %}
            </form>
        </div>

        <!-- Resumen del Carrito de Compras -->
        <div class="col-md-6">
            <h2>Resumen del Carrito de Compras</h2>
            <table class="table table-bordered mt-3">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio Unitario</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.producto.nombre }}</td>
                        <td>{{ item.cantidad }}</td>
                        <td>${{ item.producto.precio }}</td>
                        <td>${{ item.subtotal }}</td>  <!-- Mostrar el subtotal calculado -->
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3"><strong>Total Parcial</strong></td>
                        <td><strong>${{ total_parcial }}</strong></td>
                    </tr>
                    <tr>
                        <td colspan="3"><strong>IVA (5%)</strong></td>
                        <td><strong>${{ iva }}</strong></td>
                    </tr>
                    <tr>
                        <td colspan="3"><strong>Total</strong></td>
                        <td><strong>${{ total_con_iva }}</strong></td>
                    </tr>
                </tbody>
            </table>
            <form method="#" action="#">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Código de Cupón" aria-label="Código de Cupón" name="cupon">
                    <button class="btn btn-outline-secondary" type="submit">Aplicar</button>
                </div>
            </form>
            <div class="d-flex justify-content-between align-items-center mt-3">
                <a href="{% url 'metodo_de_pago' %}" class="btn btn-success {% if not formularioEnviado %}disabled{% endif %}">Proceder con el Pago</a>
                {% if not formularioEnviado %}
                <span class="text-danger">Por favor completa la dirección para proceder con el pago.</span>
                {% endif %}
                <a href="{% url 'ver_carrito' %}" class="btn btn-danger ml-auto">Regresar</a>
            </div>
            
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="text-center mb-4">
        <h2>Pasos a Seguir</h2>
    </div>
    <div class="timeline">
        <div class="step completed">
            <div class="step-number completed">1</div>
            <div class="step-content">
                <h4>Iniciar Sección</h4>
                <p>Ingresa a tu cuenta de usuario.</p>
            </div>
        </div>
        <div class="step completed">
            <div class="step-number">2</div>
            <div class="step-content">
                <h4>Carrito de Compras</h4>
                <p>Agrega productos al carrito.</p>
            </div>
        </div>
        <div class="step completed">
            <div class="step-number">3</div>
            <div class="step-content">
                <h4>Datos de Envío</h4>
                <p>Proporciona la información necesaria para el envío.</p>
            </div>
        </div>

        <div class="step ">
            <div class="step-number">3</div>
            <div class="step-content">
                <h4>Pagar</h4>
                <p>Elegir su metodo de pago</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

projectAmazon/Amazon/templates/Amazon/metodo_de_pago.html
<!-- templates/amazon/metodo_de_pago.html -->
{% extends "Amazon/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block detalle_prod %}

<style>
    .timeline {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .step {
        display: flex;
        align-items: center;
        width: 30%;
        padding: 20px;
        background-color: #f0f0f0;
        border-radius: 8px;
    }

    .step-number {
        width: 40px;
        height: 40px;
        background-color: #007bff; /* Color base de las bolitas */
        color: white;
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 50%;
        margin-right: 10px;
    }

    .step-content {
        flex: 1;
    }

    .step h4 {
        margin-bottom: 5px;
    }

    .step p {
        font-size: 0.9rem;
        color: #666;
    }

    .completed .step-number {
        background-color: #28a745; /* Color verde para los pasos completados */
    }
</style>



<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Pago con YAPE</h2>
            <div class="card">
                <div class="card-body text-center">
                    <h4 class="card-title">Escanea este QR con YAPE</h4>
                    <div class="img-wrapper">
                        <img src="{% static 'Amazon/img/QR.jpg' %}" alt="QR de YAPE" class="img-fluid" style="max-width: 50%; height: auto;">
                    </div>
                    <h3 class="card-title text-center mt-3">Monto a cobrar: ${{ total_a_pagar }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container mt-5">
    <div class="row">
        <div class=" col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body text-center">
                    <h4 class="card-title">Pago con Tarjeta de Crédito/Débito</h4>
                    <form method="post" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-8 mb-3">
                                <label for="id_numero_tarjeta" class="form-label">Número de Tarjeta</label>
                                {{ form.numero_tarjeta|add_class:"form-control" }}
                                {% for error in form.numero_tarjeta.errors %}
                                <div class="error-message text-danger">{{ error }}</div>
                                {% endfor %}
                                <div id="tipo_tarjeta" class="mt-2"></div> <!-- Contenedor para mostrar el tipo de tarjeta -->
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="id_fecha_expiracion" class="form-label">(MM/YY)</label>
                                {{ form.fecha_expiracion|add_class:"form-control" }}
                                {% for error in form.fecha_expiracion.errors %}
                                <div class="error-message text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8 mb-3">
                                <label for="id_nombre_propietario" class="form-label">Nombre del Propietario de la Tarjeta</label>
                                {{ form.nombre_propietario|add_class:"form-control" }}
                                {% for error in form.nombre_propietario.errors %}
                                <div class="error-message text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="id_cvv" class="form-label">CVV</label>
                                {{ form.cvv|add_class:"form-control" }}
                                {% for error in form.cvv.errors %}
                                <div class="error-message text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    
                        <div class="mb-1">
                            <label for="id_guardar_tarjeta" >Guardar tarjeta de forma segura para pagos futuros</label>
                            {{ form.guardar_tarjeta }}
                
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-3">
                            <button type="submit" class="btn btn-primary mt-3">Pagar ${{ total_a_pagar }}</button>
                            
                            <a href="{% url 'direccion_y_carrito' %}" class="btn btn-danger ml-auto">Regresar</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container mt-5">
    <div class="text-center mb-4">
        <h2>Pasos a Seguir</h2>
    </div>
    <div class="timeline">
        <div class="step completed">
            <div class="step-number completed">1</div>
            <div class="step-content">
                <h4>Iniciar Sección</h4>
                <p>Ingresa a tu cuenta de usuario.</p>
            </div>
        </div>
        <div class="step completed">
            <div class="step-number">2</div>
            <div class="step-content">
                <h4>Carrito de Compras</h4>
                <p>Agrega productos al carrito.</p>
            </div>
        </div>
        <div class="step completed">
            <div class="step-number">3</div>
            <div class="step-content">
                <h4>Datos de Envío</h4>
                <p>Proporciona la información necesaria para el envío.</p>
            </div>
        </div>

        <div class="step completed">
            <div class="step-number">3</div>
            <div class="step-content">
                <h4>Pagar</h4>
                <p>Elegir su metodo de pago</p>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const numeroTarjetaInput = document.getElementById('id_numero_tarjeta');
        const tipoTarjetaDiv = document.getElementById('tipo_tarjeta');

        function identificarTarjeta(numeroTarjeta) {
            numeroTarjeta = numeroTarjeta.replace(/\s|-/g, ''); // Remove spaces and dashes

            if (/^\d+$/.test(numeroTarjeta)) {
                const longitud = numeroTarjeta.length;
                if (numeroTarjeta.startsWith('4') && (longitud === 13 || longitud === 16)) {
                    return { tipo: "Visa", icono: "fab fa-cc-visa" }; // Icono de Visa
                } else if ((/^5[1-5]/.test(numeroTarjeta) || /^2(22[1-9]|2[3-9]\d|[3-6]\d{2}|7([01]\d|20))/.test(numeroTarjeta)) && longitud === 16) {
                    return { tipo: "MasterCard", icono: "fab fa-cc-mastercard" }; // Icono de MasterCard
                } else if ((numeroTarjeta.startsWith('34') || numeroTarjeta.startsWith('37')) && longitud === 15) {
                    return { tipo: "American Express", icono: "fab fa-cc-amex" }; // Icono de American Express
                } else if ((numeroTarjeta.startsWith('6011') || numeroTarjeta.startsWith('65') ||
                    /^622(12[6-9]|1[3-9]\d|[2-8]\d{2}|9[01]\d|92[0-5])/.test(numeroTarjeta) ||
                    /^64[4-9]/.test(numeroTarjeta)) && longitud === 16) {
                    return { tipo: "Discover", icono: "fab fa-cc-discover" }; // Icono de Discover
                } else if (/^35(2[89]|[3-8][0-9])/.test(numeroTarjeta) && longitud === 16) {
                    return { tipo: "JCB", icono: "fab fa-cc-jcb" }; // Icono de JCB
                } else if ((/^30[0-5]/.test(numeroTarjeta) || numeroTarjeta.startsWith('36') || numeroTarjeta.startsWith('38') || numeroTarjeta.startsWith('39')) && longitud === 14) {
                    return { tipo: "Diners Club", icono: "fab fa-cc-diners-club" }; // Icono de Diners Club
                } else {
                    return { tipo: "Tarjeta desconocida o formato inválido", icono: "fas fa-credit-card" }; // Icono predeterminado
                }
            } else {
                return { tipo: "Formato de número de tarjeta inválido", icono: "fas fa-credit-card" }; // Icono predeterminado
            }
        }

        numeroTarjetaInput.addEventListener('input', function () {
            const { tipo, icono } = identificarTarjeta(numeroTarjetaInput.value);
            tipoTarjetaDiv.innerHTML = `
                <div class="alert alert-info" role="alert">
                    <i class="${icono}"></i> ${tipo}
                </div>`;
        });
    });
</script>
{% endblock %}